# Generated by Django 3.2.7 on 2021-10-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rules_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='rules_text',
            field=models.TextField(blank=True),
        ),
    ]
