# Generated by Django 3.2.7 on 2021-10-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20211024_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rules_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
