# Generated by Django 3.2.7 on 2021-10-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20211024_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rules_link',
            field=models.URLField(default='https://gmcpas.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='game',
            name='rules_text',
            field=models.CharField(max_length=200),
        ),
    ]
