# Generated by Django 3.2.7 on 2021-10-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20211024_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='rules_link',
        ),
    ]
