# Generated by Django 3.2.7 on 2021-10-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_game_rules_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rules_text',
            field=models.TextField(),
        ),
    ]
