# Generated by Django 3.2.7 on 2021-10-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_game_rules_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rules_link',
            field=models.URLField(default='https://google.com', max_length=60),
        ),
    ]
