# Generated by Django 3.2.7 on 2021-10-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='play_complete',
            field=models.BooleanField(),
        ),
    ]
