# Generated by Django 3.2.7 on 2021-10-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_hand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hand',
        ),
    ]
