# Generated by Django 3.2.7 on 2021-10-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_delete_hand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_num', models.IntegerField()),
                ('hand_complete', models.BooleanField(null=True)),
            ],
        ),
    ]
