# Generated by Django 3.2.7 on 2021-10-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_alter_hand_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='play',
        ),
    ]
