# Generated by Django 3.2.7 on 2021-10-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_remove_hand_play'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hand',
        ),
    ]
