# Generated by Django 3.2.7 on 2021-10-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0012_playerhand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerHand',
        ),
    ]
