# Generated by Django 3.2.7 on 2021-10-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0014_playerhand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='date',
            field=models.DateField(),
        ),
    ]
