# Generated by Django 3.2.7 on 2021-10-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0015_alter_play_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='date',
        ),
    ]
