# Generated by Django 3.2.7 on 2021-10-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0016_remove_play_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='play_date',
            field=models.DateField(default='2021-10-21'),
        ),
    ]
