# Generated by Django 3.2.7 on 2021-10-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0017_play_play_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='play_date',
            field=models.DateField(default='2021-10-20'),
        ),
    ]
