# Generated by Django 3.2.7 on 2021-10-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('player', '0002_player_team'),
        ('play', '0018_alter_play_play_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('game', models.ManyToManyField(to='game.Game')),
                ('hand', models.ManyToManyField(to='play.Hand')),
                ('play', models.ManyToManyField(to='play.Play')),
                ('player', models.ManyToManyField(to='player.Player')),
            ],
        ),
    ]
