# Generated by Django 3.2.7 on 2021-10-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0019_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='play_complete',
            field=models.BooleanField(default=False),
        ),
    ]
