# Generated by Django 3.2.7 on 2021-10-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0021_alter_hand_hand_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
