# Generated by Django 3.2.7 on 2021-10-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0022_delete_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerHand',
        ),
    ]
