# Generated by Django 3.2.7 on 2021-10-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0009_delete_score'),
        ('play', '0023_delete_playerhand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hand',
        ),
    ]
