# Generated by Django 3.2.7 on 2021-11-02 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0024_auto_20211031_1418'),
        ('play', '0024_delete_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='playhand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='score.playhand'),
        ),
        migrations.AddField(
            model_name='play',
            name='playplayer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='score.playplayer'),
        ),
    ]
