# Generated by Django 3.2.7 on 2021-11-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0025_auto_20211102_1228'),
        ('play', '0025_auto_20211102_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='playhand',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.RESTRICT, to='score.playhand'),
        ),
        migrations.AlterField(
            model_name='play',
            name='playplayer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.RESTRICT, to='score.playplayer'),
        ),
    ]
