# Generated by Django 3.2.7 on 2021-11-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0026_auto_20211102_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='playhand',
        ),
        migrations.RemoveField(
            model_name='play',
            name='playplayer',
        ),
    ]
