# Generated by Django 3.2.7 on 2021-11-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0027_auto_20211102_1340'),
        ('player', '0002_player_team'),
        ('play', '0027_auto_20211102_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='hands',
            field=models.ManyToManyField(to='score.Hand'),
        ),
        migrations.AddField(
            model_name='play',
            name='players',
            field=models.ManyToManyField(to='player.Player'),
        ),
    ]
