# Generated by Django 3.2.7 on 2021-10-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('play', '0001_initial'),
        ('player', '0002_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_num', models.IntegerField()),
                ('hand_complete', models.BooleanField(default=False)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='play.play')),
                ('player', models.ManyToManyField(to='player.Player')),
            ],
        ),
    ]
