# Generated by Django 3.2.7 on 2021-10-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0004_alter_hand_hand_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='hand_complete',
            field=models.BooleanField(null=True),
        ),
    ]
