# Generated by Django 3.2.7 on 2021-10-22 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0006_delete_playerhand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hand',
        ),
    ]
