# Generated by Django 3.2.7 on 2021-10-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.BooleanField(default=False),
        ),
    ]
