# Generated by Django 3.2.7 on 2021-10-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('player', '0002_player_team'),
        ('score', '0002_auto_20211001_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='date',
        ),
        migrations.RemoveField(
            model_name='score',
            name='game_num',
        ),
        migrations.RemoveField(
            model_name='score',
            name='game',
        ),
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.ManyToManyField(to='game.Game'),
        ),
        migrations.RemoveField(
            model_name='score',
            name='player',
        ),
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.ManyToManyField(to='player.Player'),
        ),
    ]
