# Generated by Django 3.2.7 on 2021-10-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0001_initial'),
        ('play', '0001_initial'),
        ('score', '0003_auto_20211021_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='hand',
            field=models.ManyToManyField(to='hand.Hand'),
        ),
        migrations.AddField(
            model_name='score',
            name='play',
            field=models.ManyToManyField(to='play.Play'),
        ),
    ]
