# Generated by Django 3.2.7 on 2021-10-22 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_auto_20211021_1031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
