# Generated by Django 3.2.7 on 2021-10-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0008_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
