# Generated by Django 3.2.7 on 2021-10-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('score', '0009_delete_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_num', models.IntegerField()),
                ('hand_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
