# Generated by Django 3.2.7 on 2021-10-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0024_delete_hand'),
        ('game', '0012_game_rules_link'),
        ('player', '0002_player_team'),
        ('score', '0013_playerhand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('game', models.ManyToManyField(to='game.Game')),
                ('hand', models.ManyToManyField(to='score.Hand')),
                ('play', models.ManyToManyField(to='play.Play')),
                ('player', models.ManyToManyField(to='player.Player')),
            ],
        ),
    ]
