# Generated by Django 3.2.7 on 2021-10-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0014_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerHand',
        ),
    ]
