# Generated by Django 3.2.7 on 2021-10-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_team'),
        ('play', '0024_delete_hand'),
        ('score', '0015_delete_playerhand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play', models.ManyToManyField(to='play.Play')),
                ('player', models.ManyToManyField(to='player.Player')),
            ],
        ),
    ]
