# Generated by Django 3.2.7 on 2021-10-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0017_auto_20211027_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayPlayer',
        ),
    ]
