# Generated by Django 3.2.7 on 2021-10-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0024_delete_hand'),
        ('player', '0002_player_team'),
        ('score', '0018_delete_playplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(to='player.Player')),
                ('plays', models.ManyToManyField(to='play.Play')),
            ],
        ),
    ]
