# Generated by Django 3.2.7 on 2021-10-27 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0020_delete_playplayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
