# Generated by Django 3.2.7 on 2021-10-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0021_delete_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play', models.IntegerField()),
                ('player', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play', models.IntegerField()),
                ('hand', models.IntegerField()),
                ('player', models.IntegerField()),
                ('game', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
