# Generated by Django 3.2.7 on 2021-10-31 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0022_playplayer_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='play',
        ),
    ]
