# Generated by Django 3.2.7 on 2021-10-31 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_team'),
        ('score', '0023_remove_hand_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='playplayer',
            name='play',
        ),
        migrations.AlterField(
            model_name='playplayer',
            name='player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='player.player'),
        ),
        migrations.CreateModel(
            name='PlayHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='score.hand')),
                ('mmhand', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='score.mmhand')),
            ],
        ),
        migrations.CreateModel(
            name='MMPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(through='score.PlayPlayer', to='player.Player')),
            ],
        ),
        migrations.AddField(
            model_name='mmhand',
            name='hands',
            field=models.ManyToManyField(through='score.PlayHand', to='score.Hand'),
        ),
        migrations.AddField(
            model_name='playplayer',
            name='mmplayer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='score.mmplayer'),
        ),
    ]
