# Generated by Django 3.2.7 on 2021-11-02 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_team'),
        ('score', '0025_auto_20211102_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playhand',
            name='hand',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='score.hand'),
        ),
        migrations.AlterField(
            model_name='playhand',
            name='mmhand',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='score.mmhand'),
        ),
        migrations.AlterField(
            model_name='playplayer',
            name='mmplayer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='score.mmplayer'),
        ),
        migrations.AlterField(
            model_name='playplayer',
            name='player',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='player.player'),
        ),
    ]
