# Generated by Django 3.2.7 on 2021-11-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0027_auto_20211102_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_p_playid', models.IntegerField()),
            ],
        ),
    ]
