# Generated by Django 3.2.7 on 2021-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0028_playsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='playsession',
            name='in_p_handid',
            field=models.IntegerField(default=0),
        ),
    ]
