# Generated by Django 3.2.7 on 2021-11-08 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0028_auto_20211102_1347'),
        ('player', '0002_player_team'),
        ('score', '0029_playsession_in_p_handid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('hand', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='score.hand')),
                ('play', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='play.play')),
                ('player', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='player.player')),
            ],
        ),
    ]
