# Generated by Django 3.2.7 on 2021-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0030_scoretotals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoretotals',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='scoretotals',
            name='hand_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoretotals',
            name='play_total',
            field=models.IntegerField(default=0),
        ),
    ]
